name = "gemini-proxy-worker"
main = "worker.js"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables can be set here
# ALLOWED_ORIGINS = "*"
# LOG_LEVEL = "info"

# Uncomment and configure if you need custom domain routing
# [[route]]
# pattern = "your-domain.com/api/gemini/*"
# zone_name = "your-domain.com"

# Worker configuration
[env.production]
vars = { LOG_LEVEL = "error" }

[env.staging] 
vars = { LOG_LEVEL = "debug" }

# Optional: Configure analytics and monitoring
[observability]
enabled = true